Repository software-mansion-labs/expo-maps, pull requests merged in 2022-06, with the labels that each got.

#80 Add POI for Google Maps on iOS - full
  .gitattributes
  example/ios/example/ApiKeys.plist
  example/ios/example/Info.plist
  example/screens/POIExample.tsx
  example/screens/TrafficExample.tsx
  expo-maps/build/Map.js
  expo-maps/build/Map.js.map
  expo-maps/build/Map.types.d.ts
  expo-maps/build/Map.types.js.map
  expo-maps/ios/ExpoMaps/AppleMaps/AppleMapsMarkers.swift
  expo-maps/ios/ExpoMaps/AppleMaps/POIUtils/AppleMapsPOISearchCompleter.swift
  expo-maps/ios/ExpoMaps/ExpoGoogleMapsModule.swift
  expo-maps/ios/ExpoMaps/GoogleMaps/GoogleMapsMarkers.swift
  expo-maps/ios/ExpoMaps/GoogleMaps/GoogleMapsPlaces.swift
  expo-maps/ios/ExpoMaps/GoogleMaps/GoogleMapsView.swift
  expo-maps/ios/ExpoMaps/GoogleMaps/GoogleMapsViewDelegate.swift
  expo-maps/ios/ExpoMaps/GoogleMaps/PlacesUtils/GoogleMapsPlacesSearchCompleter.swift
  expo-maps/ios/ExpoMaps/GoogleMaps/PlacesUtils/GoogleMapsPlacesTokenUtils.swift
  expo-maps/ios/ExpoMaps/GoogleMaps/PlacesUtils/GooglePlacesFetchPlace.swift
  expo-maps/ios/ExpoMaps/Protocols/SearchCompleter.swift
  expo-maps/src/Map.tsx
  expo-maps/src/Map.types.ts
Labels: enhancement, ios

#82 Add Ground Overlays for Google Maps
  example/assets/newark_nj_1922.jpeg
  example/constants/ConcreteExampleScreens.ts
  example/ios/Podfile.lock
  example/ios/example.xcodeproj/project.pbxproj
  example/navigators/MainNavigator.tsx
  example/screens/OverlaysExample.tsx
  expo-maps/android/src/main/java/expo/modules/maps/ExpoGoogleMapsModule.kt
  expo-maps/android/src/main/java/expo/modules/maps/PropsData.kt
  expo-maps/android/src/main/java/expo/modules/maps/googleMaps/GoogleMapsOverlays.kt
  expo-maps/android/src/main/java/expo/modules/maps/googleMaps/GoogleMapsView.kt
  expo-maps/android/src/main/java/expo/modules/maps/interfaces/ExpoMapView.kt
  expo-maps/android/src/main/java/expo/modules/maps/interfaces/Overlays.kt
  expo-maps/build/Map.d.ts
  expo-maps/build/Map.js
  expo-maps/build/Map.js.map
  expo-maps/build/Map.types.d.ts
  expo-maps/build/Map.types.js.map
  expo-maps/build/Overlay.d.ts
  expo-maps/build/Overlay.js
  expo-maps/build/Overlay.js.map
  expo-maps/build/Utils.d.ts
  expo-maps/build/Utils.js
  expo-maps/build/Utils.js.map
  expo-maps/ios/ExpoMaps/AppleMaps/AppleMapsView.swift
  expo-maps/ios/ExpoMaps/ExpoGoogleMapsModule.swift
  expo-maps/ios/ExpoMaps/GoogleMaps/GoogleMapsOverlays.swift
  expo-maps/ios/ExpoMaps/GoogleMaps/GoogleMapsView.swift
  expo-maps/ios/ExpoMaps/PropsData.swift
  expo-maps/ios/ExpoMaps/Protocols/ExpoMapView.swift
  expo-maps/ios/ExpoMaps/Protocols/Overlays.swift
  expo-maps/src/Map.tsx
  expo-maps/src/Map.types.ts
  expo-maps/src/Overlay.ts
  expo-maps/src/Utils.ts
Labels: android, ios

#85 Implement basic callbacks
  .gitignore
  example/constants/ConcreteExampleScreens.ts
  example/ios/Podfile.lock
  example/navigators/MainNavigator.tsx
  example/package.json
  example/screens/CallbacksExample.tsx
  expo-maps/android/build.gradle
  expo-maps/android/src/main/java/expo/modules/maps/ExpoGoogleMapsModule.kt
  expo-maps/android/src/main/java/expo/modules/maps/PropsData.kt
  expo-maps/android/src/main/java/expo/modules/maps/googleMaps/GoogleMapsClusters.kt
  expo-maps/android/src/main/java/expo/modules/maps/googleMaps/GoogleMapsMarkers.kt
  expo-maps/android/src/main/java/expo/modules/maps/googleMaps/GoogleMapsView.kt
  expo-maps/android/src/main/java/expo/modules/maps/googleMaps/events/GoogleMapsCameraEventEmitter.kt
  expo-maps/android/src/main/java/expo/modules/maps/googleMaps/events/GoogleMapsCameraMoveEndedEventEmitter.kt
  expo-maps/android/src/main/java/expo/modules/maps/googleMaps/events/GoogleMapsCameraMoveStartedEventEmitter.kt
  expo-maps/android/src/main/java/expo/modules/maps/googleMaps/events/GoogleMapsEventEmitterManager.kt
  expo-maps/android/src/main/java/expo/modules/maps/googleMaps/events/MapEventsNames.kt
  expo-maps/build/Events.d.ts
  expo-maps/build/Events.js
  expo-maps/build/Events.js.map
  expo-maps/build/ExpoMaps.d.ts
  expo-maps/build/ExpoMaps.js
  expo-maps/build/ExpoMaps.js.map
  expo-maps/build/Map.d.ts
  expo-maps/build/Map.js
  expo-maps/build/Map.js.map
  expo-maps/build/Marker.d.ts
  expo-maps/build/Marker.js.map
  expo-maps/build/Utils.js
  expo-maps/build/Utils.js.map
  expo-maps/ios/ExpoMaps/AppleMaps/AppleMapsClusters.swift
  expo-maps/ios/ExpoMaps/AppleMaps/AppleMapsDelegate.swift
  expo-maps/ios/ExpoMaps/AppleMaps/AppleMapsMarkers.swift
  expo-maps/ios/ExpoMaps/AppleMaps/AppleMapsMarkersManager.swift
  expo-maps/ios/ExpoMaps/AppleMaps/AppleMapsUtils.swift
  expo-maps/ios/ExpoMaps/AppleMaps/AppleMapsView.swift
  expo-maps/ios/ExpoMaps/AppleMaps/CustomTypes/ExpoMKAnnotation.swift
  expo-maps/ios/ExpoMaps/AppleMaps/CustomTypes/ExpoMKClusterAnnotation.swift
  expo-maps/ios/ExpoMaps/ExpoAppleMapsModule.swift
  expo-maps/ios/ExpoMaps/ExpoGoogleMapsModule.swift
  expo-maps/ios/ExpoMaps/GoogleMaps/GoogleMapsClusterManagerDelegate.swift
  expo-maps/ios/ExpoMaps/GoogleMaps/GoogleMapsClusters.swift
  expo-maps/ios/ExpoMaps/GoogleMaps/GoogleMapsMarkers.swift
  expo-maps/ios/ExpoMaps/GoogleMaps/GoogleMapsMarkersManager.swift
  expo-maps/ios/ExpoMaps/GoogleMaps/GoogleMapsUtils.swift
  expo-maps/ios/ExpoMaps/GoogleMaps/GoogleMapsView.swift
  expo-maps/ios/ExpoMaps/GoogleMaps/GoogleMapsViewDelegate.swift
  expo-maps/ios/ExpoMaps/MapEventsNames.swift
  expo-maps/ios/ExpoMaps/PropsData.swift
  expo-maps/ios/ExpoMaps/Protocols/ExpoMapView.swift
  expo-maps/src/Events.ts
  expo-maps/src/ExpoMaps.ts
  expo-maps/src/Map.tsx
  expo-maps/src/Marker.ts
  expo-maps/src/Utils.ts
  package.json
  yarn.lock
Labels: enhancement

#84 Adding POI for Google Maps on Android
  .gitattributes
  example/android/app/src/main/AndroidManifest.xml
  example/android/app/src/main/assets/apikeys.properties
  expo-maps/android/build.gradle
  expo-maps/android/src/main/java/expo/modules/maps/ExpoGoogleMapsModule.kt
  expo-maps/android/src/main/java/expo/modules/maps/googleMaps/GoogleMapsMarkers.kt
  expo-maps/android/src/main/java/expo/modules/maps/googleMaps/GoogleMapsPlaces.kt
  expo-maps/android/src/main/java/expo/modules/maps/googleMaps/GoogleMapsView.kt
  expo-maps/android/src/main/java/expo/modules/maps/googleMaps/placesUtils/GoogleMapsPlacesSearchCompleter.kt
  expo-maps/android/src/main/java/expo/modules/maps/googleMaps/placesUtils/GoogleMapsPlacesTokenUtils.kt
  expo-maps/android/src/main/java/expo/modules/maps/googleMaps/placesUtils/GooglePlacesFetchPlace.kt
  yarn.lock
Labels: enhancement, android

#87 Fix: demo app controls example screen
  example/screens/ControlsExample.tsx
Labels: bug, demo app

#89 Fix typescript errors and improve example styling
  example/screens/CallbacksExample.tsx
  example/screens/POIExample.tsx
Labels: bug, demo app

#90 Create config plugin for Expo Maps
  .gitattributes
  example/.gitignore
  example/android/app/BUCK
  example/android/app/build.gradle
  example/android/app/src/debug/java/com/expo/expo/maps/ReactNativeFlipper.java
  example/android/app/src/main/AndroidManifest.xml
  example/android/app/src/main/assets/apikeys.properties
  example/android/app/src/main/java/com/expo/expo/maps/MainActivity.java
  example/android/app/src/main/java/com/expo/expo/maps/MainApplication.java
  example/android/app/src/main/java/com/expo/expo/maps/newarchitecture/MainApplicationReactNativeHost.java
  example/android/app/src/main/java/com/expo/expo/maps/newarchitecture/components/MainComponentsRegistry.java
  example/android/app/src/main/java/com/expo/expo/maps/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  example/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  example/android/app/src/main/jni/MainComponentsRegistry.h
  example/android/build.gradle
  example/app.json
  example/expo-maps.plugin.android.js
  example/expo-maps.plugin.ios.js
  example/google-maps-api-keys.json.example
  example/ios/Podfile
  example/ios/Podfile.lock
  example/ios/example.xcodeproj/project.pbxproj
  example/ios/example/ApiKeys.plist
  example/ios/example/Info.plist
  example/ios/example/Supporting/Expo.plist
  example/ios/example/example.entitlements
  example/package.json
  expo-maps/android/src/main/java/expo/modules/maps/googleMaps/GoogleMapsPlaces.kt
  expo-maps/ios/ExpoMaps/GoogleMaps/GoogleMapsView.swift
Labels: enhancement
